jobs:
- title: економіст з праці
  vacancy_number: '04602606290017'
  employer: ТОВ "СКЛЯННИЙ АЛЬЯНС"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: невизначено
  salary: 12610 грн
  phone: '+380684916873'
  description: Ведення табельного обліку, нарахування заробітної плати на підприємстві
  work_schedule: 5-денний робочий тиждень
  working_conditions: Допустимі
  requirements:
    education: Магістр
    experience: з досвідом роботи
  social_benefits: професійний розвиток
  date_posted: 28.06.26
  source: ДЦЗ
- title: інженер з комп'ютерних систем
  vacancy_number: '04602606290020'
  employer: ТОВ "СКЛЯННИЙ АЛЬЯНС"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 13100 грн
  phone: '+380684916873'
  description: Обслуговувати комп'ютерну техніку, проводити діагностику і профілактику з метою виявлення і усунення можливих причин виходу техніки із ладу
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Допустимі
  requirements:
    education: Магістр
    experience: з досвідом роботи
  social_benefits: професійний розвиток
  date_posted: 28.06.26
  source: ДЦЗ
- title: інженер-енергетик
  vacancy_number: '04602602020006'
  employer: КП "УК "ЖИЛКОМСЕРВІС"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 18095 грн
  phone: '+380684916873'
  description: організація та облік планово-експлуатаційної роботи, робота з економії енергоресурсів
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Допустимі
  requirements:
    education: Бакалавр; Магістр
    experience: з досвідом роботи
    professional_competencies: з досвідом роботи в житлово-комунальному господарстві
  social_benefits: професійний розвиток
  date_posted: 28.06.26
  source: ДЦЗ
- title: лікар-кардіолог
  vacancy_number: '04602603230003'
  employer: КП "ВІЛЬНОГІРСЬКА ЦМЛ"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 20000 грн
  phone: '+380684916873'
  description: діагностика, лікування та профілактика серцево-судинних захворювань, надання кваліфікованої медичної допомоги пацієнтам, проведення профілактичних заходів, організація реабілітації, ведення медичної документації, а також методична робота та підвищення кваліфікації молодшого медичного персоналу
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: робота, пов'язана з підвищеним нервово-емоційним та інтелектуальним навантаженням
  requirements:
    education: Магістр
    experience: без досвіду роботи
    professional_competencies: Проходження інтернатури за спеціальністю "Кардіологія", наявність сертифіката лікаря-спеціаліста та посвідчення про присвоєння (підтвердження) кваліфікаційної категорії з цієї спеціальності
  social_benefits: професійний розвиток
  date_posted: 28.06.26
  source: ДЦЗ
- title: машиніст конвеєра
  vacancy_number: '04602604230012'
  employer: ФІЛІЯ "ВІЛЬНОГІРСЬКИЙ ГІРНИЧО-МЕТАЛУРГІЙНИЙ КОМБІНАТ" АКЦІОНЕРНОГО ТОВАРИСТВА "ОБ'ЄДНАНА ГІРНИЧО-ХІМ
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: позмінна
  salary: 9154 грн
  phone: '+380684916873'
  description: керування стрічковими конвеєрами, їх обслуговування, виявлення та усунення неполадок у роботі, технічне обслуговування, прибирання робочого місця
  work_schedule: Робота змінами
  work_nature: Інше (304), строковий трудовий договір
  working_conditions: Шкідливі
  requirements:
    education: Кваліфікований робітник
    experience: без досвіду роботи
  social_benefits: забезпечення спеціальним одягом/взуттям та засобами індивідуального захисту, можливість проходження навчання на робочому місці
  date_posted: 28.06.26
  source: ДЦЗ
- title: спеціаліст державної служби (місцевого самоврядування)
  vacancy_number: '04602601120015'
  employer: ДСГП
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 13461 грн
  phone: '+380684916873'
  description: виконання обов'язків головного спеціаліста програмно-технічного забезпечення, забезпечує максимальну ефективність праці з питань, які стосуються програмно-технічного забезпечення
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Бакалавр; Магістр
    experience: без досвіду роботи
    professional_competencies: вільне володіння українською мовою, навики роботи з комп'ютером, впевнений користувач ПК (знання програм MS Office), вміння працювати з офісною технікою (копіювальна техніка, принтер, сканер тощо), знання спеціалізованих комп'ютерних програм
  social_benefits: професійний розвиток
  date_posted: 28.06.26
  source: ДЦЗ
- title: лікар-хірург
  vacancy_number: '04602605130004'
  employer: КП "ВІЛЬНОГІРСЬКА ЦМЛ"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 20000 грн
  phone: '+380684916873'
  description: призначає та обгрунтовує методику знеболювання, виконує операцію в необхідному обсязі, призначає та контролює передопераційну підготовку пацієнта та інше відповідно до посадової інструкції лікаря-хірурга
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: робота, пов'язана з підвищеним нервово-емоційним та інтелектуальним навантаженням
  requirements:
    education: Магістр
    experience: без досвіду роботи
    professional_competencies: наявність сертифіката лікаря-спеціаліста та посвідчення про присвоєння (підтвердження) кваліфікаційної категорії з цієї спеціальності; вільне володіння державною мовою та застосування її під час виконання службових обов'язків
  social_benefits: професійний розвиток
  date_posted: 30.06.26
  source: ДЦЗ
- title: лікар-інфекціоніст
  vacancy_number: '04602605120014'
  employer: КП "ВІЛЬНОГІРСЬКА ЦМЛ"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 20000 грн
  phone: '+380684916873'
  description: надає спеціалізовану медичну допомогу з інфекційною патологією, в тому числі швидку і невідкладну та інше
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: робота, пов'язана з підвищеним нервово-емоційним та інтелектуальним навантаженням
  requirements:
    education: Магістр
    experience: без досвіду роботи
    professional_competencies: наявність сертифіката лікаря-спеціаліста та посвідчення про присвоєння (підтвердження) кваліфікаційної категорії з цієї спеціальності; вільне володіння державною мовою та застосування її під час виконання службових обов'язків
  social_benefits: професійний розвиток
  date_posted: 30.06.26
  source: ДЦЗ
- title: ерготерапевт
  vacancy_number: '04602601190006'
  employer: КП "ВІЛЬНОГІРСЬКА ЦМЛ"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 20000 грн
  phone: '+380684916873'
  description: сприяє набуттю людьми з обмеженнями життєдіяльності максимального рівня функціональності та незалежності в усіх аспектах життя
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: робота, пов'язана з підвищеним нервово-емоційним та інтелектуальним навантаженням
  requirements:
    education: Магістр
    experience: без досвіду роботи
  social_benefits: професійний розвиток
  date_posted: 30.06.26
  source: ДЦЗ
- title: машиніст екскаватора одноковшового
  vacancy_number: '04602606160008'
  employer: КП "УК "ЖИЛКОМСЕРВІС"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 16000 грн
  phone: '+380684916873'
  description: планування територій, копання траншей під комунікації, завантаження сипучих матеріалів, розробка грунту 1,2 категорії
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Кваліфікований робітник
    experience: з досвідом роботи
    professional_competencies: з досвідом роботи у житлово-комунальному господарстві, мати посвідчення тракториста-машиніста з категорією А
  social_benefits: забезпечення спеціальним одягом/взуттям та засобами індивідуального захисту
  date_posted: 01.07.26
  source: ДЦЗ
- title: водій автотранспортних засобів
  vacancy_number: '04602606160013'
  employer: УАКБ ТА ЖКГ
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 8700 грн
  phone: '+380684916873'
  description: Керування колісними транспортними засобами категорії "В" за різних дорожніх умов. Виконання вимог правил дорожнього руху, правил перевезення пасажирів. Забезпечення належного технічного стану транспортного засобу. Перевірка технічного стану транспортного засобу перед виїздом на маршрут, на маршруті та після повернення з рейсу відповідно до вимог нормативно-правових актів. Забезпечення справності обладнання відповідно до встановлених вимог, що стосуються безпеки дорожнього руху, правил життєстійкості.
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Кваліфікований робітник
    experience: з досвідом роботи
    professional_competencies: посвідчення водія категорії В
  social_benefits: професійний розвиток
  date_posted: 01.07.26
  source: ДЦЗ
- title: слюсар-ремонтник
  vacancy_number: '04602606080009'
  employer: ФІЛІЯ "ВІЛЬНОГІРСЬКИЙ ГІРНИЧО-МЕТАЛУРГІЙНИЙ КОМБІНАТ" АКЦІОНЕРНОГО ТОВАРИСТВА "ОБ'ЄДНАНА ГІРНИЧО-ХІМ
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: невизначено
  salary: 8700 грн
  phone: '+380684916873'
  description: розбирає, ремонтує, складає та випробує середньої складності вузли і механізми устаткування, агрегатів та машин
  work_schedule: 5-денний робочий тиждень
  work_nature: Інше (304), строковий трудовий договір
  working_conditions: Оптимальні
  requirements:
    education: Кваліфікований робітник
    experience: без досвіду роботи
  social_benefits: забезпечення спеціальним одягом/взуттям та засобами індивідуального захисту, можливість проходження навчання на робочому місці
  date_posted: 01.07.26
  source: ДЦЗ
- title: секретар керівника (організації, підприємства, установи)
  vacancy_number: '04602606160010'
  employer: МІСЬКФІНУПРАВЛІННЯ
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 10174 грн
  phone: '+380684916873'
  description: здійснює організаційно-технічне забезпечення роботи заступника міського голови з питань діяльності виконавчих органів ради - начальника міського фінансового управління та його відділів. Забезпечує організацію діловодства в управлінні відповідно до вимог чинного законодавства. Формує справи відповідно до затвердженої номенклатури, забезпечує їх зберігання й у встановлені строки передає до архіву. Відповідає за стан зберігання документів управління. Відповідає за ведення табельного обліку.
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Бакалавр
    experience: без досвіду роботи
    professional_competencies: вільне володіння державною мовою, впевнене володіння комп'ютером — Word, Excel, робота з електронною поштою, архівна справа
  social_benefits: професійний розвиток
  date_posted: 01.07.26
  source: ДЦЗ
- title: бухгалтер
  vacancy_number: '04602605290031'
  employer: КП "ВІЛЬНОГІРСЬКА ЦМЛ"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 8700 грн
  phone: '+380684916873'
  description: нарахування заробітної плати, виконання інших розрахунків з працівниками, громадянами та юридичними особами відповідно до чинного законодавства та інше
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Магістр; Бакалавр
    experience: з досвідом роботи
    professional_competencies: знання та використання чинного законодавства у бухгалтерській сфері
  social_benefits: професійний розвиток
  date_posted: 01.07.26
  source: ДЦЗ
- title: водій автотранспортних засобів
  vacancy_number: '04602606160009'
  employer: КП "УК "ЖИЛКОМСЕРВІС"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 15000 грн
  phone: '+380684916873'
  description: збір та вивіз побутового сміття від мешканців міста
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Кваліфікований робітник
    experience: з досвідом роботи
    professional_competencies: посвідчення водія категорії С
  social_benefits: забезпечення спеціальним одягом/взуттям та засобами індивідуального захисту
  date_posted: 01.07.26
  source: ДЦЗ
- title: службовець на складі (комірник)
  vacancy_number: '04602604290009'
  employer: ВІЛЬНОГІРСЬКИЙ ЛІЦЕЙ № 4
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 9455 грн
  phone: '+380684916873'
  description: приймання, належне зберігання, облік та видача продуктів харчування, дотримуючись санітарно-гігієнічних норм (HACCP), Ведення документації, контроль терміну придатності, участь в інвентаризаціях та забезпечення кухарів сировиною, що гарантує безперебійне харчування учнів. Робота на персональному ПК, в програмах, з постачальниками та бухгалтерією.
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Кваліфікований робітник
    experience: з досвідом роботи
    professional_competencies: відповідно до профстандарту за професією; знання правил зберігання товарів та вміння вести складський облік; вільне володіння українською мовою
  social_benefits: професійний розвиток
  date_posted: 02.07.26
  source: ДЦЗ
- title: інженер-енергетик
  vacancy_number: '04602603300025'
  employer: КП "УК "ЖИЛКОМСЕРВІС"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 19888 грн
  phone: '+380684916873'
  description: здійснює роботу з організації обліку ПЕР, удосконалює систему і методи розрахунків за використання ПЕР
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Магістр; Бакалавр
    experience: з досвідом роботи
    professional_competencies: з досвідом роботи в житлово-комунальному господарстві
  social_benefits: професійний розвиток
  date_posted: 05.07.26
  source: ДЦЗ
- title: лікар-педіатр
  vacancy_number: '04602602240025'
  employer: КП "ВІЛЬНОГІРСЬКА ЦМЛ"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 20000 грн
  phone: '+380684916873'
  description: обов'язки лікаря-педіатра включають профілактику, діагностику та лікування захворювань у дітей від народження до 18 років, моніторинг їхнього фізичного та психічного розвитку, а також надання консультацій батькам щодо догляду та харчування. Педіатр проводить планові огляди, вакцинацію, призначає обстеження та лікування, а за необхідності направляє до вузьких спеціалістів
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: робота, пов'язана з підвищеним нервово-емоційним та інтелектуальним навантаженням
  requirements:
    education: Магістр
    experience: без досвіду роботи
    professional_competencies: наявність сертифіката лікаря-спеціаліста та посвідчення про присвоєння (підтвердження) кваліфікаційної категорії з цієї спеціальності
  social_benefits: професійний розвиток
  date_posted: 05.07.26
  source: ДЦЗ
- title: лікар-терапевт
  vacancy_number: '04602605120016'
  employer: КП "ВІЛЬНОГІРСЬКА ЦМЛ"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 20000 грн
  phone: '+380684916873'
  description: застосовує сучасні методи профілактики, діагностики, лікування, реабілітації та диспансеризації хворих терапевтичного профілю. Надає швидку та невідкладну медичну допомогу.
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: робота, пов'язана з підвищеним нервово-емоційним та інтелектуальним навантаженням
  requirements:
    education: Магістр
    experience: без досвіду роботи
    professional_competencies: наявність сертифіката лікаря-спеціаліста та посвідчення про присвоєння (підтвердження) кваліфікаційної категорії з цієї спеціальності; вільне володіння державною мовою та застосування її під час виконання службових обов'язків
  social_benefits: професійний розвиток
  date_posted: 05.07.26
  source: ДЦЗ
