jobs:
- title: прибиральник службових приміщень
  vacancy_number: '04602606190014'
  employer: КП "УК "ЖИЛКОМСЕРВІС"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 8700 грн
  phone: '+380684916873'
  description: вологе прибирання кабінетів, коридорів
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Допустимі
  requirements:
    education: Кваліфікований робітник
    experience: без досвіду роботи
  social_benefits: професійний розвиток
  date_posted: 18.06.26
  source: ДЦЗ
- title: лікар-педіатр
  vacancy_number: '04602602240025'
  employer: КП "ВІЛЬНОГІРСЬКА ЦМЛ"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 20000 грн
  phone: '+380684916873'
  description: обов'язки лікаря-педіатра включають профілактику, діагностику та лікування захворювань у дітей від народження до 18 років, моніторинг їхнього фізичного та психічного розвитку, а також надання консультацій батькам щодо догляду та харчування. Лікар-педіатр проводить планові огляди, вакцинацію, призначає обстеження та лікування, а за необхідності направляє до вузьких спеціалістів.
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: робота, пов'язана з підвищеним нервово-емоційним та інтелектуальним навантаженням
  requirements:
    education: Магістр
    experience: без досвіду роботи
    professional_competencies: наявність сертифіката лікаря-спеціаліста та посвідчення про присвоєння (підтвердження) кваліфікаційної категорії з цієї спеціальності
  social_benefits: професійний розвиток
  date_posted: 18.06.26
  source: ДЦЗ
- title: юрисконсульт (радник юридичний)
  vacancy_number: '04602603300027'
  employer: КП "УК "ЖИЛКОМСЕРВІС"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 23203 грн
  phone: '+380684916873'
  description: бере участь у роботі з укладання господарських договорів, підготовка висновків про їх юридичну обґрунтованість
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Магістр; Бакалавр
    experience: з досвідом роботи
  social_benefits: професійний розвиток
  date_posted: 18.06.26
  source: ДЦЗ
- title: налагоджувальник технологічного устаткування (електронна техніка)
  vacancy_number: '04602603120019'
  employer: ТОВ "СКЛЯНИЙ АЛЬЯНС"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 14200 грн
  phone: '+380684916873'
  description: обслуговування технологічного устаткування
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Допустимі
  requirements:
    education: Кваліфікований робітник
    experience: без досвіду роботи
  social_benefits: забезпечення спеціальним одягом/взуттям та засобами індивідуального захисту
  date_posted: 18.06.26
  source: ДЦЗ
- title: водій автотранспортних засобів
  vacancy_number: '04602601200012'
  employer: ФІЛІЯ "ВІЛЬНОГІРСЬКИЙ ГІРНИЧО-МЕТАЛУРГІЙНИЙ КОМБІНАТ" АКЦІОНЕРНОГО ТОВАРИСТВА "ОБ'ЄДНАНА ГІРНИЧО-ХІМ
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: невизначено
  salary: 9463 грн
  phone: '+380684916873'
  description: виконання робіт з промивання і прочищення каналізаційних мереж, водогінних і каналізаційних колодязів, відкачування води трубопроводів
  work_schedule: 5-денний робочий тиждень
  work_nature: Інше (304), строковий трудовий договір
  working_conditions: Оптимальні
  requirements:
    education: Кваліфікований робітник
    experience: без досвіду роботи
    professional_competencies: Посвідчення водія категорії B,C
  social_benefits: забезпечення спеціальним одягом/взуттям та засобами індивідуального захисту
  date_posted: 18.06.26
  source: ДЦЗ
