jobs:
- title: прибиральник службових приміщень
  vacancy_number: '04602606190014'
  employer: КП "УК "ЖИЛКОМСЕРВІС"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 8700 грн
  phone: '+380684916873'
  description: вологе прибирання кабінетів, коридорів
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Допустимі
  requirements:
    education: Кваліфікований робітник
    experience: без досвіду роботи
  social_benefits: професійний розвиток
  date_posted: 18.06.26
  source: ДЦЗ
- title: лікар-педіатр
  vacancy_number: '04602602240025'
  employer: КП "ВІЛЬНОГІРСЬКА ЦМЛ"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 20000 грн
  phone: '+380684916873'
  description: обов'язки лікаря-педіатра включають профілактику, діагностику та лікування захворювань у дітей від народження до 18 років, моніторинг їхнього фізичного та психічного розвитку, а також надання консультацій батькам щодо догляду та харчування. Лікар-педіатр проводить планові огляди, вакцинацію, призначає обстеження та лікування, а за необхідності направляє до вузьких спеціалістів.
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: робота, пов'язана з підвищеним нервово-емоційним та інтелектуальним навантаженням
  requirements:
    education: Магістр
    experience: без досвіду роботи
    professional_competencies: наявність сертифіката лікаря-спеціаліста та посвідчення про присвоєння (підтвердження) кваліфікаційної категорії з цієї спеціальності
  social_benefits: професійний розвиток
  date_posted: 18.06.26
  source: ДЦЗ
- title: юрисконсульт (радник юридичний)
  vacancy_number: '04602603300027'
  employer: КП "УК "ЖИЛКОМСЕРВІС"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 23203 грн
  phone: '+380684916873'
  description: бере участь у роботі з укладання господарських договорів, підготовка висновків про їх юридичну обґрунтованість
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Магістр; Бакалавр
    experience: з досвідом роботи
  social_benefits: професійний розвиток
  date_posted: 18.06.26
  source: ДЦЗ
- title: налагоджувальник технологічного устаткування (електронна техніка)
  vacancy_number: '04602603120019'
  employer: ТОВ "СКЛЯНИЙ АЛЬЯНС"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 14200 грн
  phone: '+380684916873'
  description: обслуговування технологічного устаткування
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Допустимі
  requirements:
    education: Кваліфікований робітник
    experience: без досвіду роботи
  social_benefits: забезпечення спеціальним одягом/взуттям та засобами індивідуального захисту
  date_posted: 18.06.26
  source: ДЦЗ
- title: водій автотранспортних засобів
  vacancy_number: '04602601200012'
  employer: ФІЛІЯ "ВІЛЬНОГІРСЬКИЙ ГІРНИЧО-МЕТАЛУРГІЙНИЙ КОМБІНАТ" АКЦІОНЕРНОГО ТОВАРИСТВА "ОБ'ЄДНАНА ГІРНИЧО-ХІМ
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: невизначено
  salary: 9463 грн
  phone: '+380684916873'
  description: виконання робіт з промивання і прочищення каналізаційних мереж, водогінних і каналізаційних колодязів, відкачування води трубопроводів
  work_schedule: 5-денний робочий тиждень
  work_nature: Інше (304), строковий трудовий договір
  working_conditions: Оптимальні
  requirements:
    education: Кваліфікований робітник
    experience: без досвіду роботи
    professional_competencies: Посвідчення водія категорії B,C
  social_benefits: забезпечення спеціальним одягом/взуттям та засобами індивідуального захисту
  date_posted: 18.06.26
  source: ДЦЗ
- title: інженер-енергетик
  vacancy_number: '04602603300025'
  employer: КП "УК "ЖИЛКОМСЕРВІС"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 19888 грн
  phone: '+380684916873'
  description: здійснює роботу з організації обліку ПЕР, удосконалює систему і методи розрахунків за використанням ПЕР
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Магістр; Бакалавр
    experience: з досвідом роботи
    professional_competencies: з досвідом роботи в житлово-комунальному господарстві
  social_benefits: професійний розвиток
  date_posted: 18.06.26
  source: ДЦЗ
- title: лікар-терапевт
  vacancy_number: '04602605120016'
  employer: КП "ВІЛЬНОГІРСЬКА ЦМЛ"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 20000 грн
  phone: '+380684916873'
  description: застосовує сучасні методи профілактики, діагностики, лікування, реабілітації та диспансеризації хворих терапевтичного профілю; надає швидку та невідкладну медичну допомогу
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: робота, пов'язана з підвищеним нервово-емоційним та інтелектуальним навантаженням
  requirements:
    education: Магістр
    experience: без досвіду роботи
    professional_competencies: наявність сертифіката лікаря-спеціаліста та посвідчення про присвоєння (підтвердження) кваліфікаційної категорії з цієї спеціальності, володіння державною мовою
  social_benefits: професійний розвиток
  date_posted: 17.06.26
  source: ДЦЗ
- title: службовець на складі (комірник)
  vacancy_number: '04602604290009'
  employer: ВІЛЬНОГІРСЬКИЙ ЛІЦЕЙ № 4
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 9455 грн
  phone: '+380684916873'
  description: приймання, належне зберігання, облік та видача продуктів харчування з дотриманням санітарно-гігієнічних норм (НАССР); ведення документації, контроль термінів придатності, участь в інвентаризації, забезпечення кухарів сировиною; робота на ПК, з постачальниками та бухгалтерією
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Кваліфікований робітник
    experience: з досвідом роботи
    professional_competencies: відповідно до профстандарту за професією; знання правил зберігання товарів та ведення складського обліку; вільне володіння українською мовою
  social_benefits: професійний розвиток
  date_posted: 16.06.26
  source: ДЦЗ
- title: спеціаліст державної служби (місцевого самоврядування)
  vacancy_number: '04602512010008'
  employer: ДСГП
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 13461 грн
  phone: '+380684916873'
  description: виконання обов'язків головного спеціаліста з питань комунікацій, інвестицій та проєктної діяльності — залучення інструментів та міжнародних інвестицій, грантів для розвитку соціально-гуманітарної сфери громади та ветеранської політики; моніторинг доступних конкурсів, грантів і проєктів
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Магістр; Бакалавр
    experience: без досвіду роботи
    professional_competencies: вільне володіння українською мовою; впевнений користувач ПК (MS Office); вміння працювати з офісною технікою; основи управління персоналом
  social_benefits: професійний розвиток
  date_posted: 16.06.26
  source: ДЦЗ
- title: сестра медична (брат медичний)
  vacancy_number: '04602512220002'
  employer: КЗДО №4
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 8700 грн
  phone: '+380684916873'
  description: щоденний нагляд за дітьми, складання меню, контроль профілактичних заходів
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Молодший спеціаліст; Фаховий молодший бакалавр; Молодший бакалавр
    experience: без досвіду роботи
  social_benefits: професійний розвиток
  date_posted: 15.06.26
  source: ДЦЗ
- title: бухгалтер
  vacancy_number: '04602605290031'
  employer: КП "ВІЛЬНОГІРСЬКА ЦМЛ"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 8700 грн
  phone: '+380684916873'
  description: нарахування заробітної плати, виконання інших розрахунків з працівниками, громадянами та юридичними особами відповідно до чинного законодавства
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Магістр; Бакалавр
    experience: з досвідом роботи
    professional_competencies: знання та використання чинного законодавства у бухгалтерській сфері
  social_benefits: професійний розвиток
  date_posted: 15.06.26
  source: ДЦЗ
- title: слюсар-ремонтник
  vacancy_number: '04602606080009'
  employer: ФІЛІЯ "ВІЛЬНОГІРСЬКИЙ ГІРНИЧО-МЕТАЛУРГІЙНИЙ КОМБІНАТ" АКЦІОНЕРНОГО ТОВАРИСТВА "ОБ'ЄДНАНА ГІРНИЧО-ХІМ
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: невизначено
  salary: 8700 грн
  phone: '+380684916873'
  description: розбирає, ремонтує, складає та випробує вузли і механізми устаткування, агрегатів та машин середньої складності
  work_schedule: 5-денний робочий тиждень
  work_nature: Інше (304), строковий трудовий договір
  working_conditions: Оптимальні
  requirements:
    education: Кваліфікований робітник
    experience: без досвіду роботи
  social_benefits: забезпечення спеціальним одягом/взуттям та засобами індивідуального захисту, можливість проходження навчання на робочому місці
  date_posted: 15.06.26
  source: ДЦЗ
- title: охоронник
  vacancy_number: '04602606010005'
  employer: ФІЛІЯ "ВІЛЬНОГІРСЬКИЙ ГІРНИЧО-МЕТАЛУРГІЙНИЙ КОМБІНАТ" АКЦІОНЕРНОГО ТОВАРИСТВА "ОБ'ЄДНАНА ГІРНИЧО-ХІМ
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: позмінна
  salary: 8700 грн
  phone: '+380684916873'
  description: фізична охорона стаціонарного об'єкту (устаткування, ліній електропередач, технічних, механічних засобів, металоконструкцій), візуальний контроль за об'єктом
  work_schedule: Робота змінами
  work_nature: Інше (304), строковий трудовий договір
  working_conditions: Оптимальні
  requirements:
    education: Кваліфікований робітник
    experience: без досвіду роботи
  social_benefits: забезпечення спеціальним одягом/взуттям та засобами індивідуального захисту, можливість проходження навчання на робочому місці
  date_posted: 15.06.26
  source: ДЦЗ
- title: інспектор з кадрів
  vacancy_number: '04602605130005'
  employer: КП "ВІЛЬНОГІРСЬКА ЦМЛ"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 8700 грн
  phone: '+380684916873'
  description: виконує обов'язки старшого інспектора з кадрів — ведення кадрового обліку працівників підприємства, персональний військовий облік призовників, військовозобов'язаних та резервістів; забезпечує відповідність кадрової документації чинному законодавству
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Бакалавр; Магістр
    experience: з досвідом роботи
  social_benefits: професійний розвиток
  date_posted: 15.06.26
  source: ДЦЗ
- title: тракторист
  vacancy_number: '04602606160006'
  employer: КП "УК "ЖИЛКОМСЕРВІС"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 15000 грн
  phone: '+380684916873'
  description: збір та вивіз побутового сміття від мешканців міста
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Кваліфікований робітник
    experience: з досвідом роботи
    professional_competencies: з досвідом роботи у житлово-комунальному господарстві; посвідчення тракториста-машиніста категорії A
  social_benefits: забезпечення спеціальним одягом/взуттям та засобами індивідуального захисту
  date_posted: 15.06.26
  source: ДЦЗ
- title: машиніст екскаватора одноковшового
  vacancy_number: '04602606160008'
  employer: КП "УК "ЖИЛКОМСЕРВІС"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 16000 грн
  phone: '+380684916873'
  description: планування території, копання траншей під комунікації, завантаження матеріалів, розробка ґрунту 1,2 категорії
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Кваліфікований робітник
    experience: з досвідом роботи
    professional_competencies: з досвідом роботи у житлово-комунальному господарстві; посвідчення тракториста-машиніста категорії A
  social_benefits: забезпечення спеціальним одягом/взуттям та засобами індивідуального захисту
  date_posted: 15.06.26
  source: ДЦЗ
- title: водій автотранспортних засобів
  vacancy_number: '04602606160009'
  employer: КП "УК "ЖИЛКОМСЕРВІС"
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 15000 грн
  phone: '+380684916873'
  description: збір та вивіз побутового сміття від мешканців міста
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Кваліфікований робітник
    experience: з досвідом роботи
    professional_competencies: посвідчення водія категорії C
  social_benefits: забезпечення спеціальним одягом/взуттям та засобами індивідуального захисту
  date_posted: 15.06.26
  source: ДЦЗ
- title: секретар керівника (організації, підприємства, установи)
  vacancy_number: '04602606160010'
  employer: МІСЬКФІНУПРАВЛІННЯ
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 10174 грн
  phone: '+380684916873'
  description: організаційно-технічне забезпечення роботи заступника міського голови з питань діяльності виконавчих органів ради, налагодження роботи фінансового управління та його відділів; організація діловодства, формування та зберігання справ згідно з номенклатурою, облік печаток і штампів, ведення табельного обліку
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Бакалавр
    experience: без досвіду роботи
    professional_competencies: вільне володіння державною мовою; впевнене володіння комп'ютером (Word, Excel), електронною поштою; архівна справа
  social_benefits: професійний розвиток
  date_posted: 15.06.26
  source: ДЦЗ
- title: адміністратор
  vacancy_number: '04602601020009'
  employer: ЛАЗУРКО ЯНА ВІКТОРІВНА
  location:
    settlement: Вільногірськ
    region: Дніпропетровська область
    district: Кам'янський район
    community: Вільногірська міська ТГ
  employment_type: повна
  salary: 10000 грн
  phone: '+380684916873'
  description: адміністратор дитячої ігрової кімнати
  work_schedule: 5-денний робочий тиждень
  work_nature: Постійний (301)
  working_conditions: Оптимальні
  requirements:
    education: Кваліфікований робітник
    experience: без досвіду роботи
  social_benefits: професійний розвиток
  date_posted: 14.06.26
  source: ДЦЗ
